# Generated by Django 5.0.2 on 2024-02-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('genders', models.CharField(max_length=1000)),
                ('poster_url', models.CharField(max_length=25500)),
                ('video_path', models.CharField(max_length=2550)),
            ],
        ),
    ]
