# Generated by Django 4.2.10 on 2024-02-22 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviefyApp', '0002_movie_rating_movie_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genders',
            new_name='genres',
        ),
    ]
